<a href="https://colab.research.google.com/github/shubh28012004/Creating_Custom_Dataset/blob/main/Creating_Custom_dataset_DPL_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating dataframe

In [10]:
import pandas as pd
import uuid # to generate random numbers
import random

In [11]:
!pip install faker

Collecting faker
  Downloading Faker-19.2.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 11.7 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)
Installing collected packages: faker
Successfully installed faker-19.2.0

In [12]:
from faker import Faker

In [37]:
#List of 6 features
features = ["id" , "gender" , "subscriber" , "name" , "rating" , "mail_id"]

In [38]:
#creating a dataframe for these features
df = pd.DataFrame(columns=features)
df

Empty DataFrame
Columns: [id, gender, subscriber, name, rating, mail_id]
Index: []

**Creating Imbalanced Data**

Generate unique identifiers

In [39]:
num_users=100
df['id']=[uuid.uuid4().hex for i in range(num_users)]
df

                                  id gender subscriber name rating mail_id
0   1f5b73f3913e4223b0e9317e9a9e9d4b    NaN        NaN  NaN    NaN     NaN
1   c976f60a7a9447c58a607dcbb662e44f    NaN        NaN  NaN    NaN     NaN
2   c9098b89c8f248cba537c0e7d77df984    NaN        NaN  NaN    NaN     NaN
3   a24e13b67f03494fb0aee04939fc5d34    NaN        NaN  NaN    NaN     NaN
4   d1bb02d1dc694c46ab1fba95262742ab    NaN        NaN  NaN    NaN     NaN
..                               ...    ...        ...  ...    ...     ...
95  5b2d8445a5674fe0aad7695700af0967    NaN        NaN  NaN    NaN     NaN
96  df7588ab400a44fbb9600cb4e778f158    NaN        NaN  NaN    NaN     NaN
97  56240dcde0c64469a13be739ce24e118    NaN        NaN  NaN    NaN     NaN
98  955d8fcf79174e6c86317d0c260fac6e    NaN        NaN  NaN    NaN     NaN
99  62542e55c9f24731b9c597f1007f5f9c    NaN        NaN  NaN    NaN     NaN

[100 rows x 6 columns]

In [40]:
df['id']=[uuid.uuid4().int for i in range(num_users)]
df

,id,gender,subscriber,name,rating,mail_id
0,134044874403385743351173730170038370079,NaN,NaN,NaN,NaN,NaN
1,132254341862293264471063839809928866982,NaN,NaN,NaN,NaN,NaN
2,109287142972232089958267033401129071676,NaN,NaN,NaN,NaN,NaN
3,76951523931670642936550844102731992975,NaN,NaN,NaN,NaN,NaN
4,2080881983474871828159157232251198661,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
95,227963685457017279880560955913560921216,NaN,NaN,NaN,NaN,NaN
96,74628708016284547499031157084319629717,NaN,NaN,NaN,NaN,NaN
97,87656298054433768852370273526364390147,NaN,NaN,NaN,NaN,NaN
98,192907478021462784747941517154569519797,NaN,NaN,NaN,NaN,NaN
99,219989264600059468129180962351070196024,NaN,NaN,NaN,NaN,NaN

to check whether ids are unique or not

In [41]:
print(df['id'].nunique()==num_users)

True

Generating Gender values

In [42]:
genders = ["mail","female","na"]
df['gender'] = random.choices(genders , weights = (45,45,10),k=num_users) #k is a parameter of num.choices
df

,id,gender,subscriber,name,rating,mail_id
0,134044874403385743351173730170038370079,mail,NaN,NaN,NaN,NaN
1,132254341862293264471063839809928866982,mail,NaN,NaN,NaN,NaN
2,109287142972232089958267033401129071676,female,NaN,NaN,NaN,NaN
3,76951523931670642936550844102731992975,female,NaN,NaN,NaN,NaN
4,2080881983474871828159157232251198661,mail,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
95,227963685457017279880560955913560921216,female,NaN,NaN,NaN,NaN
96,74628708016284547499031157084319629717,female,NaN,NaN,NaN,NaN
97,87656298054433768852370273526364390147,female,NaN,NaN,NaN,NaN
98,192907478021462784747941517154569519797,mail,NaN,NaN,NaN,NaN
99,219989264600059468129180962351070196024,female,NaN,NaN,NaN,NaN

Generating Subscriber values

In [43]:
choice = [True , False]
df['subscriber']=random.choices(choice , k=num_users)
df

,id,gender,subscriber,name,rating,mail_id
0,134044874403385743351173730170038370079,mail,False,NaN,NaN,NaN
1,132254341862293264471063839809928866982,mail,True,NaN,NaN,NaN
2,109287142972232089958267033401129071676,female,True,NaN,NaN,NaN
3,76951523931670642936550844102731992975,female,False,NaN,NaN,NaN
4,2080881983474871828159157232251198661,mail,False,NaN,NaN,NaN
...,...,...,...,...,...,...
95,227963685457017279880560955913560921216,female,False,NaN,NaN,NaN
96,74628708016284547499031157084319629717,female,False,NaN,NaN,NaN
97,87656298054433768852370273526364390147,female,True,NaN,NaN,NaN
98,192907478021462784747941517154569519797,mail,False,NaN,NaN,NaN
99,219989264600059468129180962351070196024,female,True,NaN,NaN,NaN

Generating name values

In [44]:
#instantitaing faker
faker = Faker(locale = "EN_IN")
def name_gen(gender):
  if gender == 'male':
    return faker.name_male()
  elif gender == 'female':
    return faker.name_female()
  return faker.name()

#Generating names
df['name'] = [name_gen(i) for i in df['gender']]
df

,id,gender,subscriber,name,rating,mail_id
0,134044874403385743351173730170038370079,mail,False,Oorja Master,NaN,NaN
1,132254341862293264471063839809928866982,mail,True,Badal Chauhan,NaN,NaN
2,109287142972232089958267033401129071676,female,True,Damini Bose,NaN,NaN
3,76951523931670642936550844102731992975,female,False,Yashvi Bhakta,NaN,NaN
4,2080881983474871828159157232251198661,mail,False,Amani Dora,NaN,NaN
...,...,...,...,...,...,...
95,227963685457017279880560955913560921216,female,False,Samaira Karnik,NaN,NaN
96,74628708016284547499031157084319629717,female,False,Aarna Ratta,NaN,NaN
97,87656298054433768852370273526364390147,female,True,Lavanya Grover,NaN,NaN
98,192907478021462784747941517154569519797,mail,False,Myra Majumdar,NaN,NaN
99,219989264600059468129180962351070196024,female,True,Devansh Venkatesh,NaN,NaN

Generating rating values

In [45]:
rating = [1,2,3,4,5]
df['rating'] = random.choices(rating , weights = (45,45,20,30,10), k = num_users)
df

,id,gender,subscriber,name,rating,mail_id
0,134044874403385743351173730170038370079,mail,False,Oorja Master,2,NaN
1,132254341862293264471063839809928866982,mail,True,Badal Chauhan,4,NaN
2,109287142972232089958267033401129071676,female,True,Damini Bose,4,NaN
3,76951523931670642936550844102731992975,female,False,Yashvi Bhakta,3,NaN
4,2080881983474871828159157232251198661,mail,False,Amani Dora,2,NaN
...,...,...,...,...,...,...
95,227963685457017279880560955913560921216,female,False,Samaira Karnik,4,NaN
96,74628708016284547499031157084319629717,female,False,Aarna Ratta,3,NaN
97,87656298054433768852370273526364390147,female,True,Lavanya Grover,4,NaN
98,192907478021462784747941517154569519797,mail,False,Myra Majumdar,4,NaN
99,219989264600059468129180962351070196024,female,True,Devansh Venkatesh,1,NaN

Generating mail ids using faker

In [48]:
import numpy as np
from faker import Faker
import pandas as pd

# Create a Faker object
fake = Faker()

def faker_categorical(gender, seed=None):
    np.random.seed(seed)
    fake.seed_instance(seed)
    gender = np.random.choice(["M", "F"], p=[0.5, 0.5])
    return {
        "First name": fake.first_name_male() if gender == "M" else fake.first_name_female(),
        "Last name": fake.last_name(),
        "E-mail": fake.ascii_email(),
    }

# Sample DataFrame with a 'gender' column
data = {
    "gender": ["M", "F", "M", "F", "M"]
}
df = pd.DataFrame(data)

# Use the faker_categorical function to populate the 'mail_id' column
df['mail_id'] = df['gender'].apply(lambda gender: faker_categorical(gender))

# If you want to access individual fields like 'First name', 'Last name', and 'E-mail', you can use DataFrame apply
df['First name'] = df['mail_id'].apply(lambda x: x['First name'])
df['Last name'] = df['mail_id'].apply(lambda x: x['Last name'])
df['E-mail'] = df['mail_id'].apply(lambda x: x['E-mail'])

# Drop the 'mail_id' column if you don't need it anymore
df.drop(columns=['mail_id'], inplace=True)

print(df)

  gender First name Last name                                 E-mail
0      M      Jesse     Adams  claytonjennifer@daugherty-watkins.com
1      F     Donald  Martinez                donnafisher@hotmail.com
2      M     George    Walker                   wangjose@gilbert.biz
3      F      Kevin     Mason               torrescourtney@davis.org
4      M    Matthew   Vincent             robbinskaren@hernandez.com

Convert dataframe to dataset

In [26]:
df.to_csv('dpldataset.csv')

In [27]:
#viewing the saved csv file
csv_df = pd.read_csv('dpldataset.csv',index_col=0)
csv_df

,id,gender,subscriber,name,rating,subscribe
0,193523885092967108439296418598900754613,na,True,Zara Chakrabarti,4,True
1,10144726555132264307230221639785238922,mail,True,Romil Cherian,4,True
2,90630107075514180075554420338379732769,female,True,Ira Chaudry,4,False
3,271863784305964989290876944764028910019,female,True,Divit Vaidya,1,False
4,110933698658170285914850204273575534603,na,True,Sana Dora,1,False
...,...,...,...,...,...,...
95,293494184682972107229839936848693640806,na,False,Prerak Sura,2,True
96,125569192081806276038504732611198485069,female,True,Diya Wadhwa,1,False
97,231430366168867478929003269532198166425,mail,True,Samar Karnik,4,False
98,236559186088323759585967121960597159001,female,True,Ivan Korpal,5,False
99,322874359636471798419925787227213518114,na,False,Badal Virk,2,False